title: CFL Wiki
version: "0.1.2"
description: "Community makerspace wiki for Chico Fab Lab - tools, projects, and resources"
# For local development: baseurl: ""
# For GitHub Pages: baseurl: "/chicofablab.github.io"
baseurl: ""
url: "http://localhost:4000"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

collections:
  wiki:
    output: true
    permalink: /wiki/:name/

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
