title: CFL Wiki
baseurl: "/chicofablab.github.io"
url: "https://ctavolazzi.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

collections:
  wiki:
    output: true
    permalink: /wiki/:name/

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
